# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_xbar_0/DataSniffer_xbar_0.xci
# IP: The module: 'DataSniffer_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_xbar_0/DataSniffer_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataSniffer_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_xbar_0/DataSniffer_xbar_0.xci
# IP: The module: 'DataSniffer_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_xbar_0/DataSniffer_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataSniffer_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
