# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/git/SDPU/DataSniffer/DataSniffer.cache/wt [current_project]
set_property parent.project_path C:/git/SDPU/DataSniffer/DataSniffer.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_repo_paths {
  c:/git/SDPU/ip_repo/PeselSercher_1.0
  c:/git/SDPU/ip_repo/axis_fifo_1.0
} [current_project]
set_property ip_output_repo c:/git/SDPU/DataSniffer/DataSniffer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/hdl/DataSniffer_wrapper.v
add_files C:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/DataSniffer.bd
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_processing_system7_0_0/DataSniffer_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_axi_dma_0_0/DataSniffer_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_axi_dma_0_0/DataSniffer_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_axi_dma_0_0/DataSniffer_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_rst_ps7_0_50M_0/DataSniffer_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_rst_ps7_0_50M_0/DataSniffer_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_rst_ps7_0_50M_0/DataSniffer_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_xbar_0/DataSniffer_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_auto_ds_0/DataSniffer_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_auto_ds_0/DataSniffer_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_auto_pc_0/DataSniffer_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_auto_us_0/DataSniffer_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_auto_us_0/DataSniffer_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_auto_us_1/DataSniffer_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_auto_us_1/DataSniffer_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/ip/DataSniffer_auto_pc_1/DataSniffer_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/DataSniffer_ooc.xdc]
set_property is_locked true [get_files C:/git/SDPU/DataSniffer/DataSniffer.srcs/sources_1/bd/DataSniffer/DataSniffer.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top DataSniffer_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef DataSniffer_wrapper.dcp

catch { report_utilization -file DataSniffer_wrapper_utilization_synth.rpt -pb DataSniffer_wrapper_utilization_synth.pb }
