# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DataSniffer/DataSniffer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer || ORIG_REF_NAME==DataSniffer}]

# IP: bd/DataSniffer/ip/DataSniffer_processing_system7_0_0/DataSniffer_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_processing_system7_0_0 || ORIG_REF_NAME==DataSniffer_processing_system7_0_0}]

# IP: bd/DataSniffer/ip/DataSniffer_xlconcat_0_0/DataSniffer_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_xlconcat_0_0 || ORIG_REF_NAME==DataSniffer_xlconcat_0_0}]

# IP: bd/DataSniffer/ip/DataSniffer_axi_dma_0_0/DataSniffer_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_axi_dma_0_0 || ORIG_REF_NAME==DataSniffer_axi_dma_0_0}]

# IP: bd/DataSniffer/ip/DataSniffer_axi_mem_intercon_0/DataSniffer_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_axi_mem_intercon_0 || ORIG_REF_NAME==DataSniffer_axi_mem_intercon_0}]

# IP: bd/DataSniffer/ip/DataSniffer_rst_ps7_0_50M_0/DataSniffer_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_rst_ps7_0_50M_0 || ORIG_REF_NAME==DataSniffer_rst_ps7_0_50M_0}]

# IP: bd/DataSniffer/ip/DataSniffer_ps7_0_axi_periph_0/DataSniffer_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_ps7_0_axi_periph_0 || ORIG_REF_NAME==DataSniffer_ps7_0_axi_periph_0}]

# IP: bd/DataSniffer/ip/DataSniffer_xbar_0/DataSniffer_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_xbar_0 || ORIG_REF_NAME==DataSniffer_xbar_0}]

# IP: bd/DataSniffer/ip/DataSniffer_PeselSercher_0_0/DataSniffer_PeselSercher_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_PeselSercher_0_0 || ORIG_REF_NAME==DataSniffer_PeselSercher_0_0}]

# IP: bd/DataSniffer/ip/DataSniffer_auto_ds_0/DataSniffer_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_auto_ds_0 || ORIG_REF_NAME==DataSniffer_auto_ds_0}]

# IP: bd/DataSniffer/ip/DataSniffer_auto_pc_0/DataSniffer_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_auto_pc_0 || ORIG_REF_NAME==DataSniffer_auto_pc_0}]

# IP: bd/DataSniffer/ip/DataSniffer_auto_us_0/DataSniffer_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_auto_us_0 || ORIG_REF_NAME==DataSniffer_auto_us_0}]

# IP: bd/DataSniffer/ip/DataSniffer_auto_us_1/DataSniffer_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_auto_us_1 || ORIG_REF_NAME==DataSniffer_auto_us_1}]

# IP: bd/DataSniffer/ip/DataSniffer_auto_pc_1/DataSniffer_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataSniffer_auto_pc_1 || ORIG_REF_NAME==DataSniffer_auto_pc_1}]

# XDC: bd/DataSniffer/DataSniffer_ooc.xdc
